/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Account.CompanyAccountController;
import Controller.Account.PersonalAccountController;
import Controller.Account.SavingAccountController;
import Controller.Account.TransactionController;
import Controller.DB.DBConnectionController;
import Controller.Fields.TextFieldsCorrectnessController;
import Controller.Owner.OwnerController;
import Model.Exceptions.NotEnoughMoneyEx;
import View.ErrorMessagesAccount.MessageAccountDepositeTooShort;
import static View.ErrorMessagesAccount.MessageAccountDepositeTooShort.jTextField1;
import View.ErrorMessagesAccount.MessageAccountNoMoney;
import static View.LoginFrame.LoginPeselTextbox1;
import static View.LoginFrame.LoginUsernameTextbox;
import static View.RegisterFrame.mf;
import com.sun.glass.events.KeyEvent;
import javax.swing.JFrame;


/**
 *
 * @author mateu
 */
public class AccountFrame extends javax.swing.JFrame {

    /**
     * Creates new form AccountFrame
     */
    DBConnectionController con = new DBConnectionController();
    AccountFrameDelete afd = new AccountFrameDelete();
    public static MessageAccountNoMoney noMoney = new MessageAccountNoMoney();
    public static FirstFrame ff = new FirstFrame();
    OwnerController o = new OwnerController();
    SavingAccountController sac = new SavingAccountController();
    PersonalAccountController pac = new PersonalAccountController();
    CompanyAccountController cac = new CompanyAccountController();
    public static MessageAccountDepositeTooShort mad = new MessageAccountDepositeTooShort(); 
    public static TransactionHistory history = new TransactionHistory();
    public static FirstFrame f = new FirstFrame();
    
    public AccountFrame() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelRegisterMinimalize = new javax.swing.JLabel();
        jLabelRegisterClose = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        AccountLogoutButton = new javax.swing.JButton();
        AccountDeleteButton = new javax.swing.JButton();
        AccountWithdrawButton = new javax.swing.JButton();
        AccountDepositeButton = new javax.swing.JButton();
        firstname = new javax.swing.JTextField();
        secondname = new javax.swing.JTextField();
        pesel1 = new javax.swing.JTextField();
        street = new javax.swing.JTextField();
        housenumber = new javax.swing.JTextField();
        postalcode = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        AccountShowDataButton = new javax.swing.JButton();
        AccountNumberField = new javax.swing.JTextField();
        AccountBalanceField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        DepositeField = new javax.swing.JTextField();
        WithdrawField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        AccountTransactionButton = new javax.swing.JButton();
        TransactionField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        AccountNumberTransactField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        InterestField = new javax.swing.JTextField();
        AccountAddInterestButton = new javax.swing.JButton();
        HisotryButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(248, 148, 6));

        jLabelRegisterMinimalize.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelRegisterMinimalize.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegisterMinimalize.setText("-");
        jLabelRegisterMinimalize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelRegisterMinimalize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegisterMinimalizeMouseClicked(evt);
            }
        });

        jLabelRegisterClose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelRegisterClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegisterClose.setText("X");
        jLabelRegisterClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelRegisterClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegisterCloseMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Welcome in your Bank Account");

        nameLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("User");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelRegisterMinimalize)
                .addGap(18, 18, 18)
                .addComponent(jLabelRegisterClose)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelRegisterMinimalize, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelRegisterClose, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nameLabel))))
                .addGap(484, 484, 484))
        );

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));

        AccountLogoutButton.setBackground(new java.awt.Color(242, 38, 19));
        AccountLogoutButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AccountLogoutButton.setForeground(new java.awt.Color(255, 255, 255));
        AccountLogoutButton.setText("Logout");
        AccountLogoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AccountLogoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccountLogoutButtonMouseClicked(evt);
            }
        });

        AccountDeleteButton.setBackground(new java.awt.Color(242, 38, 19));
        AccountDeleteButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AccountDeleteButton.setForeground(new java.awt.Color(255, 255, 255));
        AccountDeleteButton.setText("Delete");
        AccountDeleteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AccountDeleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccountDeleteButtonMouseClicked(evt);
            }
        });

        AccountWithdrawButton.setBackground(new java.awt.Color(34, 121, 44));
        AccountWithdrawButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AccountWithdrawButton.setForeground(new java.awt.Color(255, 255, 255));
        AccountWithdrawButton.setText("Withdraw");
        AccountWithdrawButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AccountWithdrawButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccountWithdrawButtonMouseClicked(evt);
            }
        });

        AccountDepositeButton.setBackground(new java.awt.Color(34, 121, 44));
        AccountDepositeButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AccountDepositeButton.setForeground(new java.awt.Color(255, 255, 255));
        AccountDepositeButton.setText("Deposite");
        AccountDepositeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AccountDepositeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccountDepositeButtonMouseClicked(evt);
            }
        });

        firstname.setEditable(false);

        secondname.setEditable(false);

        pesel1.setEditable(false);

        street.setEditable(false);

        housenumber.setEditable(false);

        postalcode.setEditable(false);

        city.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Your Personal Data:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("First Name:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Last Name:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PESEL:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Street:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("House Number:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Postal Code:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("City:");

        AccountShowDataButton.setBackground(new java.awt.Color(34, 167, 240));
        AccountShowDataButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AccountShowDataButton.setForeground(new java.awt.Color(255, 255, 255));
        AccountShowDataButton.setText("Show Data");
        AccountShowDataButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AccountShowDataButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccountShowDataButtonMouseClicked(evt);
            }
        });

        AccountNumberField.setEditable(false);

        AccountBalanceField.setEditable(false);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Bank Account Number:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Bank Account Balance:");

        DepositeField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DepositeFieldKeyTyped(evt);
            }
        });

        WithdrawField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                WithdrawFieldKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Amount to deposite:");

        AccountTransactionButton.setBackground(new java.awt.Color(34, 121, 44));
        AccountTransactionButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AccountTransactionButton.setForeground(new java.awt.Color(255, 255, 255));
        AccountTransactionButton.setText("Transact");
        AccountTransactionButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AccountTransactionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccountTransactionButtonMouseClicked(evt);
            }
        });

        TransactionField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TransactionFieldKeyTyped(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Amount to withdraw:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Amount to transact:");

        AccountNumberTransactField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AccountNumberTransactFieldKeyTyped(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Account Number You Want To Send Money:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Add Interest:");

        InterestField.setEditable(false);
        InterestField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                InterestFieldKeyTyped(evt);
            }
        });

        AccountAddInterestButton.setBackground(new java.awt.Color(34, 121, 44));
        AccountAddInterestButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AccountAddInterestButton.setForeground(new java.awt.Color(255, 255, 255));
        AccountAddInterestButton.setText("Add Interest");
        AccountAddInterestButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AccountAddInterestButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccountAddInterestButtonMouseClicked(evt);
            }
        });

        HisotryButton.setBackground(new java.awt.Color(34, 167, 240));
        HisotryButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        HisotryButton.setForeground(new java.awt.Color(255, 255, 255));
        HisotryButton.setText("Show History");
        HisotryButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HisotryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HisotryButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(14, 14, 14))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel17))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InterestField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DepositeField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WithdrawField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TransactionField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(89, 89, 89)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AccountTransactionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AccountWithdrawButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AccountDepositeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AccountAddInterestButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(101, 101, 101))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(AccountNumberField, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                                    .addComponent(AccountBalanceField)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(AccountNumberTransactField, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(54, 54, 54)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(AccountShowDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(secondname, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pesel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(street, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(postalcode, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(housenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(390, 390, 390)
                .addComponent(HisotryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(213, 213, 213)
                .addComponent(AccountLogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AccountDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AccountNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(secondname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AccountBalanceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pesel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(street, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(housenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(AccountDepositeButton)
                            .addComponent(DepositeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(AccountAddInterestButton)
                            .addComponent(InterestField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(AccountWithdrawButton)
                            .addComponent(WithdrawField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AccountShowDataButton)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(postalcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TransactionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15))
                            .addComponent(AccountTransactionButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(AccountNumberTransactField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HisotryButton)
                        .addGap(34, 34, 34))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AccountLogoutButton)
                            .addComponent(AccountDeleteButton))
                        .addGap(37, 37, 37))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelRegisterMinimalizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegisterMinimalizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelRegisterMinimalizeMouseClicked

    private void jLabelRegisterCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegisterCloseMouseClicked
        this.dispose();
        AccountNumberField.setText("");
        AccountBalanceField.setText("");
        firstname.setText("");
        secondname.setText("");
        pesel1.setText("");
        street.setText("");
        housenumber.setText("");
        postalcode.setText("");
        city.setText("");
       
    }//GEN-LAST:event_jLabelRegisterCloseMouseClicked
    int x1,y1;
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-x1, y-y1);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        x1 = evt.getX();
        y1 = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void AccountLogoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountLogoutButtonMouseClicked
        this.dispose();
        AccountNumberField.setText("");
        AccountBalanceField.setText("");
        firstname.setText("");
        secondname.setText("");
        pesel1.setText("");
        street.setText("");
        housenumber.setText("");
        postalcode.setText("");
        city.setText("");
       
    }//GEN-LAST:event_AccountLogoutButtonMouseClicked

    private void AccountDeleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountDeleteButtonMouseClicked
        this.dispose();
        afd.setVisible(true);
        afd.setExtendedState(JFrame.NORMAL);   
    }//GEN-LAST:event_AccountDeleteButtonMouseClicked

    private void AccountDepositeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountDepositeButtonMouseClicked
        
        TextFieldsCorrectnessController controller = new TextFieldsCorrectnessController();
        controller.chechCorrectnessDeposite(DepositeField);
        try
        {
            double depositeSum = Double.parseDouble(DepositeField.getText());
            sac.setBalance(depositeSum);
            con.connectSaveOwnerBalance(sac,o.getsPeselController());
            DepositeField.setText("");
            con.connectAccountGetBalanceAndNumber(sac, LoginPeselTextbox1);
            AccountBalanceField.setText(String.valueOf(sac.getBalance()));
        }
        catch(NumberFormatException ex)
        {
            ex.getMessage();
            mad.setVisible(true);
        }   
    }//GEN-LAST:event_AccountDepositeButtonMouseClicked

    private void AccountShowDataButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountShowDataButtonMouseClicked
        String pesel = LoginPeselTextbox1.getText();
        
        con.connectGetOwnerData(o,pesel);
        
        firstname.setText(o.getsFirstNameController());
        secondname.setText(o.getsLastNameController());
        pesel1.setText(o.getsPeselController());
        street.setText(o.getsStreetController());
        housenumber.setText(o.getsHouseNumberController());
        postalcode.setText(String.valueOf(o.getiPostalCodeController()));
        city.setText(o.getsCityController());
    }//GEN-LAST:event_AccountShowDataButtonMouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        con.connectGetOwnerData(o, LoginPeselTextbox1.getText());
        nameLabel.setText(o.getsFirstNameController()+"!");
        con.connectAccountGetBalanceAndNumber(sac, LoginPeselTextbox1);
        AccountNumberField.setText(sac.getBankAccountNumber());
        AccountBalanceField.setText(String.valueOf(sac.getBalance()));
        con.connectGetAccountData(sac, LoginPeselTextbox1.getText());
       
        if(sac.getTypeId()==1)
        {
            InterestField.setText(String.valueOf(sac.getInterest()));
        }
        else if(sac.getTypeId() == 2)
        {
            sac.setInterest(0.01);
            InterestField.setText(String.valueOf(sac.getInterest()));
        }
        else
        {
            sac.setInterest(0.03);
            InterestField.setText(String.valueOf(sac.getInterest()));
        }
        
    }//GEN-LAST:event_formComponentShown

    private void DepositeFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DepositeFieldKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)|| (c==KeyEvent.VK_BACKSPACE) || (c==KeyEvent.VK_DELETE)|| (c==KeyEvent.VK_PERIOD)))
        {
            evt.consume();
            mf.setVisible(true);
        }        
    }//GEN-LAST:event_DepositeFieldKeyTyped

    private void WithdrawFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_WithdrawFieldKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)|| (c==KeyEvent.VK_BACKSPACE) || (c==KeyEvent.VK_DELETE)|| (c==KeyEvent.VK_PERIOD)))
        {
            evt.consume();
            mf.setVisible(true);
        }
    }//GEN-LAST:event_WithdrawFieldKeyTyped

    private void TransactionFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TransactionFieldKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)|| (c==KeyEvent.VK_BACKSPACE) || (c==KeyEvent.VK_DELETE)|| (c==KeyEvent.VK_PERIOD)))
        {
            evt.consume();
            mf.setVisible(true);
        }
    }//GEN-LAST:event_TransactionFieldKeyTyped

    private void AccountNumberTransactFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AccountNumberTransactFieldKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)|| (c==KeyEvent.VK_BACKSPACE) || (c==KeyEvent.VK_DELETE)|| (c==KeyEvent.VK_PERIOD)))
        {
            evt.consume();
            mf.setVisible(true);
        }
    }//GEN-LAST:event_AccountNumberTransactFieldKeyTyped

    private void InterestFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InterestFieldKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)|| (c==KeyEvent.VK_BACKSPACE) || (c==KeyEvent.VK_DELETE) || (c==KeyEvent.VK_PERIOD)))
        {
            evt.consume();
            mf.setVisible(true);
        }
    }//GEN-LAST:event_InterestFieldKeyTyped

    private void AccountAddInterestButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountAddInterestButtonMouseClicked
        con.connectGetAccountData(sac, LoginPeselTextbox1.getText());
        sac.addInterest();
        con.connectSaveOwnerBalance(sac, LoginPeselTextbox1.getText());
        con.connectAccountGetBalanceAndNumber(sac, LoginPeselTextbox1);
        AccountBalanceField.setText(String.valueOf(sac.getBalance()));
        System.out.println(sac.getBalance());
    }//GEN-LAST:event_AccountAddInterestButtonMouseClicked

    private void AccountWithdrawButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountWithdrawButtonMouseClicked
       try
        {
            double WithdrawSum = Double.parseDouble(WithdrawField.getText());
            con.connectAccountGetBalanceAndNumber(sac, LoginPeselTextbox1);
            sac.withdraw(WithdrawSum);
            con.connectWithdrawOwnerMoney(sac, LoginPeselTextbox1.getText());

            WithdrawField.setText("");
            con.connectAccountGetBalanceAndNumber(sac, LoginPeselTextbox1);
            AccountBalanceField.setText(String.valueOf(sac.getBalance()));
        }
        catch(NumberFormatException ex)
        {
            ex.getMessage();
            mad.setVisible(true);
        } 
        catch (NotEnoughMoneyEx ex) 
        {
            ex.getMessage();
            noMoney.setVisible(true);
        }   
    }//GEN-LAST:event_AccountWithdrawButtonMouseClicked

    private void AccountTransactionButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountTransactionButtonMouseClicked
        if(AccountNumberTransactField.getDocument().getLength()==26)
        {
            try
            {
                TransactionController trans = new TransactionController();
                trans.setSendAmount(Double.parseDouble(TransactionField.getText()));
                trans.setReceiverAccountNumber(AccountNumberTransactField.getText());

                con.connectGetAccountData(sac, LoginUsernameTextbox.getText());
              
                sac.transaction(trans);
                
                con.connectWithdrawOwnerMoney(sac, LoginPeselTextbox1.getText());
                con.connectSaveOwnerBalanceTransaction(trans, AccountNumberTransactField.getText());
                con.connectGetTransactAccountData(trans);
                System.out.println(trans.getReceiverLastName());
                System.out.println(trans.getReceiverName());
                con.connectSaveTransaction(trans,LoginPeselTextbox1.getText());
                
                TransactionField.setText("");
                AccountNumberTransactField.setText("");
                con.connectAccountGetBalanceAndNumber(sac, LoginPeselTextbox1);
                AccountBalanceField.setText(String.valueOf(sac.getBalance()));
            }
            catch(NumberFormatException ex)
            {
                ex.getMessage();
                mad.setVisible(true);
            } 
             catch (NotEnoughMoneyEx ex) 
            {
                ex.getMessage();
                noMoney.setVisible(true);
            } 
        }
        else
        {
            jTextField1.setText("YOU MUST TYPE ACCOUNT NUMBER!");
            mad.setVisible(true);

        }
       
    }//GEN-LAST:event_AccountTransactionButtonMouseClicked

    private void HisotryButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HisotryButtonMouseClicked
       history.setVisible(true);
    }//GEN-LAST:event_HisotryButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccountAddInterestButton;
    private javax.swing.JTextField AccountBalanceField;
    private javax.swing.JButton AccountDeleteButton;
    private javax.swing.JButton AccountDepositeButton;
    private javax.swing.JButton AccountLogoutButton;
    private javax.swing.JTextField AccountNumberField;
    private javax.swing.JTextField AccountNumberTransactField;
    private javax.swing.JButton AccountShowDataButton;
    private javax.swing.JButton AccountTransactionButton;
    private javax.swing.JButton AccountWithdrawButton;
    private javax.swing.JTextField DepositeField;
    private javax.swing.JButton HisotryButton;
    private javax.swing.JTextField InterestField;
    private javax.swing.JTextField TransactionField;
    private javax.swing.JTextField WithdrawField;
    private javax.swing.JTextField city;
    private javax.swing.JTextField firstname;
    private javax.swing.JTextField housenumber;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelRegisterClose;
    private javax.swing.JLabel jLabelRegisterMinimalize;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField pesel1;
    private javax.swing.JTextField postalcode;
    private javax.swing.JTextField secondname;
    private javax.swing.JTextField street;
    // End of variables declaration//GEN-END:variables
}
