/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.DB.DBConnectionController;
import Controller.Fields.TextFieldsCorrectnessController;
import View.ErrorMessagesLogin.MessageLOGINLoginTooLong;
import View.ErrorMessagesLogin.MessageLOGINLoginTooShort;
import View.ErrorMessagesLogin.MessageLOGINPasswordTooLong;
import View.ErrorMessagesLogin.MessageLOGINPasswordTooShort;
import View.ErrorMessagesLogin.MessageLOGINWrongLogniOrPassword;
import static View.RegisterFrame.mf;
import com.sun.glass.events.KeyEvent;
import javax.swing.JFrame;


/**
 *
 * @author mateu
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public static MessageLOGINPasswordTooLong pTooLong = new MessageLOGINPasswordTooLong();
    public static MessageLOGINPasswordTooShort pTooShort = new MessageLOGINPasswordTooShort();
    public static MessageLOGINLoginTooLong lTooLong = new MessageLOGINLoginTooLong();
    public static MessageLOGINLoginTooShort lTooShort = new MessageLOGINLoginTooShort();
    public static MessageLOGINWrongLogniOrPassword wrongpass = new MessageLOGINWrongLogniOrPassword();
    public static AccountFrame af = new AccountFrame();
    public LoginFrame() {
        initComponents();
        this.setLocationRelativeTo(this);//na środku jest okno
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelLoginClose = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelLoginMinimalize = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        LoginUsernameTextbox = new javax.swing.JTextField();
        LoginPasswordTextbox = new javax.swing.JPasswordField();
        LoginCancelButton = new javax.swing.JButton();
        LoginLoginButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelNewAccount = new javax.swing.JLabel();
        LoginRefreshButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        LoginPeselTextbox1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(248, 148, 6));
        jPanel1.setPreferredSize(new java.awt.Dimension(140, 50));

        jLabelLoginClose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelLoginClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLoginClose.setText("X");
        jLabelLoginClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelLoginClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLoginCloseMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Login");

        jLabelLoginMinimalize.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelLoginMinimalize.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLoginMinimalize.setText("-");
        jLabelLoginMinimalize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelLoginMinimalize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLoginMinimalizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelLoginMinimalize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelLoginClose)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelLoginClose)
                        .addComponent(jLabelLoginMinimalize)))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("User Number:");

        LoginUsernameTextbox.setBackground(new java.awt.Color(108, 122, 137));
        LoginUsernameTextbox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LoginUsernameTextbox.setForeground(new java.awt.Color(255, 255, 255));
        LoginUsernameTextbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                LoginUsernameTextboxKeyTyped(evt);
            }
        });

        LoginPasswordTextbox.setBackground(new java.awt.Color(108, 122, 137));
        LoginPasswordTextbox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LoginPasswordTextbox.setForeground(new java.awt.Color(255, 255, 255));
        LoginPasswordTextbox.setToolTipText("");
        LoginPasswordTextbox.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        LoginCancelButton.setBackground(new java.awt.Color(242, 38, 19));
        LoginCancelButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LoginCancelButton.setForeground(new java.awt.Color(255, 255, 255));
        LoginCancelButton.setText("Cancel");
        LoginCancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginCancelButtonActionPerformed(evt);
            }
        });

        LoginLoginButton.setBackground(new java.awt.Color(34, 167, 240));
        LoginLoginButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LoginLoginButton.setForeground(new java.awt.Color(255, 255, 255));
        LoginLoginButton.setText("Login");
        LoginLoginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginLoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginLoginButtonMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Create a new");

        jLabelNewAccount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNewAccount.setForeground(new java.awt.Color(0, 153, 255));
        jLabelNewAccount.setText("Account");
        jLabelNewAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelNewAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNewAccountMouseClicked(evt);
            }
        });

        LoginRefreshButton.setBackground(new java.awt.Color(34, 121, 44));
        LoginRefreshButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LoginRefreshButton.setForeground(new java.awt.Color(255, 255, 255));
        LoginRefreshButton.setText("Refresh");
        LoginRefreshButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginRefreshButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginRefreshButtonMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PESEL:");

        LoginPeselTextbox1.setBackground(new java.awt.Color(108, 122, 137));
        LoginPeselTextbox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LoginPeselTextbox1.setForeground(new java.awt.Color(255, 255, 255));
        LoginPeselTextbox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                LoginPeselTextbox1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel4)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LoginUsernameTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LoginPasswordTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNewAccount))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(LoginCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(LoginRefreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(LoginLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(LoginPeselTextbox1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginUsernameTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginPasswordTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(LoginPeselTextbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginCancelButton)
                    .addComponent(LoginLoginButton)
                    .addComponent(LoginRefreshButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelNewAccount))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelLoginCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLoginCloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabelLoginCloseMouseClicked

    private void jLabelLoginMinimalizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLoginMinimalizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelLoginMinimalizeMouseClicked

    private void LoginCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginCancelButtonActionPerformed
        this.dispose();        // zamyka tylko jedni okienko i zasoby jakie ono pobiera
    }//GEN-LAST:event_LoginCancelButtonActionPerformed

    private void jLabelNewAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNewAccountMouseClicked
            FirstFrame.l.setVisible(true);
            FirstFrame.l.setExtendedState(JFrame.NORMAL);   
            this.dispose();
    }//GEN-LAST:event_jLabelNewAccountMouseClicked
    int x1,y1;
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-x1, y-y1);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        x1 = evt.getX();
        y1 = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void LoginRefreshButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginRefreshButtonMouseClicked
        LoginUsernameTextbox.setText(null);
        LoginPasswordTextbox.setText(null);
    }//GEN-LAST:event_LoginRefreshButtonMouseClicked

    private void LoginLoginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginLoginButtonMouseClicked
        TextFieldsCorrectnessController c1 = new TextFieldsCorrectnessController(); 
        c1.checkCorrectnessLogin(LoginUsernameTextbox, LoginPasswordTextbox);
        if(c1.isGood())
        {
            DBConnectionController c = new DBConnectionController();
            boolean check =c.checkUser(LoginUsernameTextbox, LoginPasswordTextbox,LoginPeselTextbox1);
            if(check)
            {
                LoginUsernameTextbox.setText("");
                LoginPasswordTextbox.setText("");
                this.dispose();
                af.setVisible(true);
            }
            else
            {
                wrongpass.setVisible(true);
                LoginUsernameTextbox.setText("");
                LoginPasswordTextbox.setText("");
            }
        }
        
    }//GEN-LAST:event_LoginLoginButtonMouseClicked

    private void LoginUsernameTextboxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LoginUsernameTextboxKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)|| (c==KeyEvent.VK_BACKSPACE) || (c==KeyEvent.VK_DELETE)))
        {
            evt.consume();
            mf.setVisible(true);
        }
    }//GEN-LAST:event_LoginUsernameTextboxKeyTyped

    private void LoginPeselTextbox1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LoginPeselTextbox1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginPeselTextbox1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginCancelButton;
    private javax.swing.JButton LoginLoginButton;
    private javax.swing.JPasswordField LoginPasswordTextbox;
    public static javax.swing.JTextField LoginPeselTextbox1;
    private javax.swing.JButton LoginRefreshButton;
    public static javax.swing.JTextField LoginUsernameTextbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelLoginClose;
    private javax.swing.JLabel jLabelLoginMinimalize;
    private javax.swing.JLabel jLabelNewAccount;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
